export const APP_NAME = 'Valora'
export const WEB_LINK = 'https://valoraapp.com/'
export const CELO_FAUCET_LINK = 'https://celo.org/app'
export const CELO_TERMS_LINK = 'https://celo.org/terms'
export const TOS_LINK = 'https://valoraapp.com/terms'
export const PRIVACY_LINK = 'https://valoraapp.com/privacy'
export const FAQ_LINK = 'https://valoraapp.com/faq'
export const HELP_LINK = 'https://valoraapp.com/support'
export const FUNDING_LINK = 'https://valoraapp.com/fund-wallet'
export const CELO_REWARDS_LINK = 'https://celo.org/celo-rewards-education'
export const FORUM_LINK = 'https://forum.celo.org/c/valora/8'
export const CELO_SUPPORT_EMAIL_ADDRESS = 'support@valoraapp.com'
export const SUPERCHARGE_LEARN_MORE = 'https://valoraapp.com/support/supercharge-learn-more'
export const INVITE_REWARDS_LEARN_MORE = 'https://valoraapp.com/support/invite-rewards-learn-more'
export const DAPPS_LEARN_MORE = 'https://valoraapp.com/support/dapps-learn-more'
export const SWAP_LEARN_MORE = 'https://valoraapp.com/support/swap-learn-more'
export const TRANSACTION_FEES_LEARN_MORE =
  'https://valoraapp.com/support/transaction-fees-learn-more'
